Controllers/ProdutoController.cs
using DemeTech.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Security.Claims;

namespace DemeTech.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly DemetechContext _context;

        public ProdutoController(DemetechContext context)
        {
            _context = context;
        }
        public IActionResult CatalogoDeProdutos(string mensagem)
        {
            List<Produto> alimentos = new List<Produto>();
            var banco = _context.AlimentosParaVendas.ToList();
            foreach (var item in banco)
            {

                Produto produto = new Produto();
                produto.CodigoAlimento = item.CodigoAlimento;
                produto.NomeDoProduto = item.NomeDoProduto;
                produto.Categoria = item.Categoria;
                produto.QuantidadeEstoque = item.QuantidadeEstoque;
                produto.Descricao = item.Descricao;
                produto.Peso = item.Peso;
                produto.Preco = item.Preco;
                produto.Imagem = item.Imagem;

                alimentos.Add(produto);
            }
            ViewBag.Message = mensagem;
            return View(alimentos);
        }

        [Authorize]
        public IActionResult Carrinho(string mensagem)
        {
            ClaimsPrincipal usuarioAtual = new ClaimsPrincipal();
            usuarioAtual = this.User;
            string id = usuarioAtual.FindFirst(ClaimTypes.NameIdentifier).Value;
            List<ItensCarrinho> itensCarrinhos = new List<ItensCarrinho>();
            var procura = _context.Carrinho.FirstOrDefault(x => x.Cnpj == id);
            var carrinho = _context.ItensCarrinhos.Where(x => x.Carrinho == procura).ToList();
            var alimentoEmBd = _context.AlimentosParaVendas.ToList();
            foreach(var item in carrinho)
            {
                ItensCarrinho car = new ItensCarrinho();
                car.CodigoProdutoNavigation = item.CodigoProdutoNavigation;
                car.Carrinho = item.Carrinho;
                car.ItensId = item.ItensId;
                itensCarrinhos.Add(car);
            }
            ViewBag.Message = mensagem;
            ViewBag.QtdProduto = procura.QuantidadeDeProdutos;
            ViewBag.PrecoTotal = procura.PrecoTotal;
            return View(itensCarrinhos);
        }
        [Authorize]
        public IActionResult AdicionarProduto(string codigo)
        {
            var alimentoEmBd = _context.AlimentosParaVendas.SingleOrDefault(x => x.CodigoAlimento == codigo);
            ClaimsPrincipal usuarioAtual = new ClaimsPrincipal();
            usuarioAtual = this.User;
            string id = usuarioAtual.FindFirst(ClaimTypes.NameIdentifier).Value;
            var procura = _context.Carrinho.SingleOrDefault(x => x.Cnpj == id);
            CarrinhoDeProduto carrinhoCliente = new CarrinhoDeProduto();
            carrinhoCliente = procura;

            ItensCarrinho item = new ItensCarrinho();
            if (alimentoEmBd != null)
            {
                item.CodigoProdutoNavigation = alimentoEmBd;
                item.Carrinho = procura;
                carrinhoCliente.PrecoTotal += alimentoEmBd.Preco;
                carrinhoCliente.QuantidadeDeProdutos++;

                _context.ItensCarrinhos.Add(item);
                _context.Carrinho.Update(carrinhoCliente);
                _context.SaveChanges();

                string mensagem = "Produto adicionado ao carrinho";
                /*É necessário o new para que o método de redirecionar entenda que o parâmetro adicionado
                não seja um caminho para outra página.*/
                return RedirectToAction("CatalogoDeProdutos", new { mensagem });
            }
            else
            {
                string mensagem = "Produto indisponível";
                return RedirectToAction("CatalogoDeProdutos", new {mensagem});
            }
        }

        public IActionResult RemoverProduto(int id, int carrinhoId, double alimentoPreco)
        {
            var item = _context.ItensCarrinhos.SingleOrDefault(item => item.ItensId == id);
            var carrinhoCliente = _context.Carrinho.SingleOrDefault(carrinho => carrinho.CarrinhoId == carrinhoId);
            carrinhoCliente.PrecoTotal -= alimentoPreco;
            carrinhoCliente.QuantidadeDeProdutos--;
            _context.ItensCarrinhos.Remove(item);
            _context.Carrinho.Update(carrinhoCliente);
            _context.SaveChanges();
            string mensagem = "Produto removido do carrinho";
            return RedirectToAction("Carrinho", new { mensagem });
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemeTech</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DemeTech.styles.css" asp-append-version="true" />
    <link rel="icon" type="image/png" href="~/images/trevo.ico" sizes="32x32">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/trevo.ico" class="icon mb-1 me-1" />DemeTech
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-md-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 gap-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">
                                <img src="~/images/casaIcone.png" class="icon mb-1 me-1" />Início
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="CatalogoDeProdutos">
                                <img src="~/images/comidaIcone.png" class="icon mb-1 me-1" />Catálogo de produtos
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Carrinho">
                                <img src="~/images/carrinhoIcone.png" class="icon mb-1 me-1" />Carrinho
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Suporte">
                                <img src="~/images/ajudaIcone.png" class="icon mb-1 me-1" />Suporte
                            </a>
                        </li>
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3 mb-5">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted text-center mt-5">
        <div class="container">
            &copy; 2024 - DemeTech - <a asp-area="" asp-controller="Home" asp-action="Suporte">Precisa de ajuda?</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>