Controllers/ContaController.cs
using Microsoft.AspNetCore.Mvc;
using DemeTech.Models;
using System.Data.SqlClient;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
namespace DemeTech.Controllers
{
    public class ContaController : Controller
    {
		private readonly DemetechContext _context;


		public ContaController(DemetechContext context)
		{
			_context = context;
		}

        public IActionResult Registrar()
        {
            ModelState.Clear();
			return View();
        }
		public IActionResult EfetuarLogin()
        {
			return View();
		}

        //Página só acessada se o cliente for autorizado
        [HttpPost]
        public IActionResult EfetuarLogin(ClienteLogar conta)
		{ 
			//O ModelState.IsValid verifica se os dados recebidos são válidos de acordo com as restrições
			//de validação definidas na classe do objeto.
            if (!ModelState.IsValid)
            {
				return View();
			}
            else
            {
				//Como o tipo numeric é decimal, foi necessário mudar cnpj para decimal para esta
				//verificação funcionar.
				//O método abaixo procura o primeiro cnpj e a primeira senha que for igual ao informado
				//pelo usuário.
				//Se achar a conta, o usuário será logado. Caso o contrário, uma mensagem de erro irá
				//aparecer para ele.

				var usuario = _context.Clientes.Where(x => x.Cnpj == conta.Cnpj && x.Senha == conta.Senha).FirstOrDefault();
                if(usuario != null)
                {
					ViewBag.Message = "Login realizado com sucesso";
					ModelState.Clear();
					//Adicionando o email do usuário como o nome a ser exibido.
					var receba = new List<Claim>
					{
						new Claim(ClaimTypes.NameIdentifier, usuario.Cnpj),
						new Claim(ClaimTypes.Name, usuario.Email)
					};
					//Irá logar o usuário e criar seus cookies
					var recebaIdentidade = new ClaimsIdentity(receba, CookieAuthenticationDefaults.AuthenticationScheme);
					HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(recebaIdentidade));
					return Redirect("../Produto/CatalogoDeProdutos");
				}
				else
				{
					ViewBag.Message = "Login ou senha errados.";
					ModelState.Clear();
					return View();
				}

			}
        }

        [HttpPost]
        public IActionResult Registrar(Cliente conta)
        {
            //O ModelState.IsValid verifica se os dados recebidos são válidos de acordo com as restrições
            //de validação definidas na classe do objeto.
            if (!ModelState.IsValid)
			{
				return View(conta);
            }
            else
            {
				//Procura na base de dados se o cnpj já está registrado.
				//Se não estiver registrado, o método Find() irá retornar null.
				var procura = _context.Clientes.Find(conta.Cnpj);

				//Criando a conta do cliente junto ao carrinho único dele.
				//Depois que a criação for um sucesso, será retornado uma mensagem informando o usuário
				//que o procedimento foi um sucesso.
				if (procura == null)
				{
					Cliente cliente = new Cliente();
					cliente.Cnpj = conta.Cnpj;
					cliente.Nome = conta.Nome;
					cliente.Email = conta.Email;
					cliente.Endereco = conta.Endereco;
					cliente.Senha = conta.Senha;
					cliente.Numero = conta.Numero;
					_context.Clientes.Add(cliente);
					CarrinhoDeProduto carrinho = new CarrinhoDeProduto();
					carrinho.Cnpj = cliente.Cnpj;
					carrinho.QuantidadeDeProdutos = 0;
					carrinho.PrecoTotal = 0;
					_context.Carrinho.Add(carrinho);
					_context.SaveChanges();
					ViewBag.Message = "Cadastro realizado com sucesso.";
					ModelState.Clear();
					return View();
				}
				ViewBag.Message = "Esse Cnpj já está cadastrado.";
				return View();
			}
			
        }

		[HttpPost]
		public IActionResult EfetuarLogout()
		{
			//Desconectando a conta do usuário
			HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
			return Redirect("../Home/Index");
		}


	}
}

Views/Conta/EfetuarLogin.cshtml
@{
	ViewData["Title"] = "Logar";
}
@model DemeTech.Models.ClienteLogar;

<section class="container section-conta d-flex flex-column justify-content-center align-items-center mb-4">

	@if (ViewBag.Message == "Login realizado com sucesso.")
	{
		<div class="aviso w-100 alert alert-success alert-dismissible fade show" role="alert">
			<strong>@ViewBag.Message</strong>
			<button type="button" class="btn-close" data-bs-dismiss="alert" arial-label="Close"></button>
		</div>
	}
	else if (ViewBag.Message != null)
	{
		<div class="aviso w-100 alert alert-warning alert-dismissible fade show" role="alert">
			<strong>@ViewBag.Message</strong>
			<button type="button" class="btn-close" data-bs-dismiss="alert" arial-label="Close"></button>
		</div>
	}
	<form asp-action="EfetuarLogin" class="account-form shadow-lg w-100 border border-2 rounded-3 border-dark-subtle" asp-controller="Conta" method="post">
		<div class="text-center">
			<h1>Login</h1>
		</div>
		<label>CNPJ</label>
		<input type="number" class="form-control" placeholder="000000000000"asp-for="Cnpj" />
		<span class="d-block text-danger" asp-validation-for="Cnpj"></span>
		<label class="mt-4">Senha</label>
		<input type="password" class="form-control" placeholder="Senha" asp-for="Senha" />
		<span class="d-block text-danger" asp-validation-for="Senha"></span>
		<div class="d-grid gap-2">
			<button class="btn btn-success mt-4" type="submit">Confirmar</button>
			<a class="btn btn-success" asp-action="Registrar">Cadastrar nova conta?</a>
		</div>
	</form>
</section>

<!--Validação em lado cliente com javascript disponibilizado pelo asp.net-->
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

Views/Conta/Registrar.cshtml
@{
	ViewData["Title"] = "Criar conta";
}
@model DemeTech.Models.Cliente;

<section class="container section-conta d-flex flex-column align-items-center mb-4">
	@if (ViewBag.Message == "Cadastro realizado com sucesso.")
	{
		<div class="aviso w-100 alert alert-success alert-dismissible fade show" role="alert">
			<strong>@ViewBag.Message <a class="" asp-action="EfetuarLogin" asp-controller="Conta">Clique aqui para realizar seu login.</a></strong>
			<button type="button" class="btn-close" data-bs-dismiss="alert" arial-label="Close"></button>
		</div>
	}else if(ViewBag.Message != null)
	{
		<div class="aviso w-100 alert alert-warning alert-dismissible fade show" role="alert">
			<strong>@ViewBag.Message <a asp-action="EfetuarLogin" asp-controller="Conta">Gostaria de fazer login?</a></strong>
			<button type="button" class="btn-close" data-bs-dismiss="alert" arial-label="Close"></button>
		</div>
	}
	<form asp-action="Registrar" class="account-form shadow-lg w-100 border border-2 rounded-3 border-dark-subtle" asp-controller="Conta" method="post">
		<div class="text-center">
			<h1>Criar conta</h1>
		</div>

		<label>CNPJ</label>
		<input type="number" placeholder="000000000000" class="form-control" asp-for="Cnpj" />
		<span class="d-block text-danger" asp-validation-for="Cnpj"></span>

		<label class="mt-4">Nome</label>
		<input type="text" class="form-control" placeholder="Nome" asp-for="Nome" />
		<span class="d-block text-danger" asp-validation-for="Nome"></span>

		<label class="mt-4">Endereço</label>
		<input type="text" class="form-control" placeholder="Endereço" asp-for="Endereco" />
		<span class="d-block text-danger" asp-validation-for="Endereco"></span>

		<label class="mt-4">Número de telefone</label>
		<input type="number" class="form-control"  placeholder="00 000000000" asp-for="Numero" />
		<span class="d-block text-danger" asp-validation-for="Numero"></span>

		<label class="mt-4">Email</label>
		<input type="email" class="form-control"  placeholder="exemplo@email.com" asp-for="Email" />
		<span class="d-block text-danger" asp-validation-for="Email"></span>

		<label class="mt-4">Senha</label>
		<input type="password" class="form-control"  placeholder="Senha" asp-for="Senha" />
		<span class="d-block text-danger" asp-validation-for="Senha"></span>

		<div class="d-grid gap-2">
			<button class="btn btn-success mt-3" type="submit">Confirmar</button>
			<a class="btn btn-success"asp-controller="Conta" asp-action="EfetuarLogin">Já tem uma conta?</a>
		</div>
	</form>
</section>

<!--Validação em lado cliente com javascript disponibilizado pelo asp.net-->
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>