Models/Produto.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Drawing;

namespace DemeTech.Models
{
    public class Produto
    {
        private string? codigoAlimento;
        private string? nomeDoProduto;
        private string? descricao;
        private double? preco;
        private string? categoria;
        private int? quantidadeEstoque;
        private double? peso;
        private byte[]? imagem;

        public byte[]? Imagem { get { return imagem; } set { imagem = value; } }

        public Produto() {

        }

        public string? CodigoAlimento { get { return codigoAlimento; } set { codigoAlimento = value; } }
        public string? NomeDoProduto { get { return nomeDoProduto; } set { nomeDoProduto = value; } }
        public string? Descricao { get { return descricao; } set { descricao = value; } }
        public double? Preco { get { return preco; } set { preco = value; } } 
        public string? Categoria { get { return categoria; } set {   categoria = value; } }
        
        public int? QuantidadeEstoque { get { return quantidadeEstoque; } set { quantidadeEstoque = value; } }
        public double? Peso { get { return peso; } set { peso = value; } }
    }
}

Controllers/CheckoutController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DemeTech.Controllers
{
    public class CheckoutController : Controller
    {
        [Authorize]
        public IActionResult Pagamento()
        {
            return View();
        }
    }
}

Controllers/ProdutoController.cs
using DemeTech.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Security.Claims;

namespace DemeTech.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly DemetechContext _context;

        public ProdutoController(DemetechContext context)
        {
            _context = context;
        }
        public IActionResult CatalogoDeProdutos(string mensagem)
        {
            List<Produto> alimentos = new List<Produto>();
            var banco = _context.AlimentosParaVendas.ToList();
            foreach (var item in banco)
            {

                Produto produto = new Produto();
                produto.CodigoAlimento = item.CodigoAlimento;
                produto.NomeDoProduto = item.NomeDoProduto;
                produto.Categoria = item.Categoria;
                produto.QuantidadeEstoque = item.QuantidadeEstoque;
                produto.Descricao = item.Descricao;
                produto.Peso = item.Peso;
                produto.Preco = item.Preco;
                produto.Imagem = item.Imagem;

                alimentos.Add(produto);
            }
            ViewBag.Message = mensagem;
            return View(alimentos);
        }

        [Authorize]
        public IActionResult Carrinho(string mensagem)
        {
            ClaimsPrincipal usuarioAtual = new ClaimsPrincipal();
            usuarioAtual = this.User;
            string id = usuarioAtual.FindFirst(ClaimTypes.NameIdentifier).Value;
            List<ItensCarrinho> itensCarrinhos = new List<ItensCarrinho>();
            var procura = _context.Carrinho.FirstOrDefault(x => x.Cnpj == id);
            var carrinho = _context.ItensCarrinhos.Where(x => x.Carrinho == procura).ToList();
            var alimentoEmBd = _context.AlimentosParaVendas.ToList();
            foreach(var item in carrinho)
            {
                ItensCarrinho car = new ItensCarrinho();
                car.CodigoProdutoNavigation = item.CodigoProdutoNavigation;
                car.Carrinho = item.Carrinho;
                car.ItensId = item.ItensId;
                itensCarrinhos.Add(car);
            }
            ViewBag.Message = mensagem;
            ViewBag.QtdProduto = procura.QuantidadeDeProdutos;
            ViewBag.PrecoTotal = procura.PrecoTotal;
            return View(itensCarrinhos);
        }
        [Authorize]
        public IActionResult AdicionarProduto(string codigo)
        {
            var alimentoEmBd = _context.AlimentosParaVendas.SingleOrDefault(x => x.CodigoAlimento == codigo);
            ClaimsPrincipal usuarioAtual = new ClaimsPrincipal();
            usuarioAtual = this.User;
            string id = usuarioAtual.FindFirst(ClaimTypes.NameIdentifier).Value;
            var procura = _context.Carrinho.SingleOrDefault(x => x.Cnpj == id);
            CarrinhoDeProduto carrinhoCliente = new CarrinhoDeProduto();
            carrinhoCliente = procura;

            ItensCarrinho item = new ItensCarrinho();
            if (alimentoEmBd != null)
            {
                item.CodigoProdutoNavigation = alimentoEmBd;
                item.Carrinho = procura;
                carrinhoCliente.PrecoTotal += alimentoEmBd.Preco;
                carrinhoCliente.QuantidadeDeProdutos++;

                _context.ItensCarrinhos.Add(item);
                _context.Carrinho.Update(carrinhoCliente);
                _context.SaveChanges();

                string mensagem = "Produto adicionado ao carrinho";
                /*É necessário o new para que o método de redirecionar entenda que o parâmetro adicionado
                não seja um caminho para outra página.*/
                return RedirectToAction("CatalogoDeProdutos", new { mensagem });
            }
            else
            {
                string mensagem = "Produto indisponível";
                return RedirectToAction("CatalogoDeProdutos", new {mensagem});
            }
        }

        public IActionResult RemoverProduto(int id, int carrinhoId, double alimentoPreco)
        {
            var item = _context.ItensCarrinhos.SingleOrDefault(item => item.ItensId == id);
            var carrinhoCliente = _context.Carrinho.SingleOrDefault(carrinho => carrinho.CarrinhoId == carrinhoId);
            carrinhoCliente.PrecoTotal -= alimentoPreco;
            carrinhoCliente.QuantidadeDeProdutos--;
            _context.ItensCarrinhos.Remove(item);
            _context.Carrinho.Update(carrinhoCliente);
            _context.SaveChanges();
            string mensagem = "Produto removido do carrinho";
            return RedirectToAction("Carrinho", new { mensagem });
        }

    }
}

Views/Produto/Carrinho.cshtml
@{
    ViewData["Title"] = "Carrinho";
}
@model List<ItensCarrinho>
<div class="container">
    <h1>Seus itens</h1>
    @if (ViewBag.Message != null)
    {
        <div class="aviso w-100 alert alert-success alert-dismissible fade show" role="alert">
            <strong>@ViewBag.Message</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" arial-label="Close"></button>
        </div>
    }

    <hr>
    <h3>Total de itens no carrinho: @ViewBag.QtdProduto</h3>
    <h3>Preço Total: R$@ViewBag.PrecoTotal</h3>
    <a class="btn btn-success" asp-controller="Checkout" asp-action="Pagamento">Comprar tudo</a>
</div>


<section class="container mb-4 mt-3">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        @foreach (var carrinho in Model)
        {
            if (carrinho.CodigoProdutoNavigation.Imagem != null)
            {
                var base64 = Convert.ToBase64String(carrinho.CodigoProdutoNavigation.Imagem);
                var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                <div class="col">
                    <div class="card card-menu h-100">
                        <img src="@imgsrc" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">@carrinho.CodigoProdutoNavigation.NomeDoProduto</h5>
                            <p class="card-text">Código do alimento: @carrinho.CodigoProdutoNavigation.CodigoAlimento</p>
                            <p class="card-text">Descrição: @carrinho.CodigoProdutoNavigation.Descricao</p>
                            <p class="card-text">Preço: R$@carrinho.CodigoProdutoNavigation.Preco</p>
                            <p class="card-text">Peso: @carrinho.CodigoProdutoNavigation.Peso</p>
                            <a class="btn btn-success" asp-action="RemoverProduto" asp-route-alimentoPreco="@carrinho.CodigoProdutoNavigation.Preco" asp-route-id="@carrinho.ItensId" asp-route-carrinhoId="@carrinho.Carrinho.CarrinhoId">Remover do carrinho</a>
                        </div>
                    </div>
                </div>
            }
            else
            {
                <div class="col">
                    <div class="card card-menu h-100">
                        <img src="~/images/alimentos.jpg" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">@carrinho.CodigoProdutoNavigation.NomeDoProduto</h5>
                            <p class="card-text">Código do alimento: @carrinho.CodigoProdutoNavigation.CodigoAlimento</p>
                            <p class="card-text">Descrição: @carrinho.CodigoProdutoNavigation.Descricao</p>
                            <p class="card-text">Preço: R$@carrinho.CodigoProdutoNavigation.Preco</p>
                            <p class="card-text">Peso: @carrinho.CodigoProdutoNavigation.Peso</p>
                            <a class="btn btn-success" asp-action="RemoverProduto" asp-route-alimentoPreco="@carrinho.CodigoProdutoNavigation.Preco" asp-route-id="@carrinho.ItensId" asp-route-carrinhoId="@carrinho.Carrinho.CarrinhoId">Remover do carrinho</a>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</section>

Views/Produto/CatalogoDeProdutos.cshtml
@{
    ViewData["Title"] = "Catalogo de produtos";
}
@model List<Produto>

<div class="container">
    <h1>Alimentos</h1>
    @if(ViewBag.Message != null)
    {
        <div class="aviso w-100 alert alert-success alert-dismissible fade show" role="alert">
            <strong>@ViewBag.Message</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" arial-label="Close"></button>
        </div>
    }
</div>
<section class="container">
    <ul class="nav nav-tabs mb-4" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" id="todos-tab" data-bs-toggle="tab" data-bs-target="#todos-tab-pane" type="button" role="tab" aria-controls="todos-tab-pane" aria-selected="true">Todos Alimentos disponíveis</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="frutas-tab" data-bs-toggle="tab" data-bs-target="#frutas-tab-pane" type="button" role="tab" aria-controls="frutas-tab-pane" aria-selected="false">Frutas</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="verduras-tab" data-bs-toggle="tab" data-bs-target="#verduras-tab-pane" type="button" role="tab" aria-controls="verduras-tab-pane" aria-selected="false">Verduras</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="raizes-tab" data-bs-toggle="tab" data-bs-target="#raizes-tab-pane" type="button" role="tab" aria-controls="raizes-tab-pane" aria-selected="false">Raízes</button>
        </li>
    </ul>
    <div class="tab-content mb-4" id="myTabContent">
        <div class="tab-pane fade show active" id="todos-tab-pane" role="tabpanel" aria-labelledby="todos-tab" tabindex="0">
            <div class="row row-cols-1 row-cols-md-3 g-4">
                @foreach (var produto in Model){
                    if (produto.Imagem != null)
                    {
                        var base64 = Convert.ToBase64String(produto.Imagem);
                        var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                        <div class="col">
                            <div class="card card-menu h-100">
                                <img src="@imgsrc" class="card-img-top" alt="...">
                                <div class="card-body">
                                    <h5 class="card-title">@produto.NomeDoProduto</h5>
                                    <p class="card-text">Código do alimento: @produto.CodigoAlimento</p>
                                    <p class="card-text">Descrição: @produto.Descricao</p>
                                    <p class="card-text">Preço: R$@produto.Preco</p>
                                    <p class="card-text">Peso: @produto.Peso</p>
                                    <a class="btn btn-success d-block mb-2" asp-action="AdicionarProduto" asp-route-codigo="@produto.CodigoAlimento">Adicionar ao carrinho</a>
                                    <a class="btn btn-success d-block" asp-controller="Checkout" asp-action="Pagamento">Comprar produto</a>
                                </div>
                            </div>
                        </div>
                    }
                    else
                    {
                    <div class="col">
                        <div class="card card-menu h-100">
                                <img src="~/images/alimentos.jpg" class="card-img-top" alt="...">
                                <div class="card-body">
                                    <h5 class="card-title">@produto.NomeDoProduto</h5>
                                    <p class="card-text">Código do alimento: @produto.CodigoAlimento</p>
                                    <p class="card-text">Descrição: @produto.Descricao</p>
                                    <p class="card-text">Preço: R$@produto.Preco</p>
                                    <p class="card-text">Peso: @produto.Peso</p>
                                    <a class="btn btn-success d-block mb-2" asp-action="AdicionarProduto" asp-route-codigo="@produto.CodigoAlimento">Adicionar ao carrinho</a>
                                    <a class="btn btn-success d-block" asp-controller="Checkout" asp-action="Pagamento">Comprar produto</a>
                                </div>
                            </div>
                    </div> 
                    }
                }
            </div>
        </div>
        <div class="tab-pane fade" id="frutas-tab-pane" role="tabpanel" aria-labelledby="frutas-tab" tabindex="0">
            <div class="row row-cols-1 row-cols-md-3 g-4">
                @foreach (var produto in Model)
                {
                    if (produto.Categoria.ToLower().Equals("fruta"))
                    {
                        if (produto.Imagem != null)
                        {
                            var base64 = Convert.ToBase64String(produto.Imagem);
                            var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                            <div class="col">
                                <div class="card card-menu h-100">
                                    <img src="@imgsrc" class="card-img-top" alt="...">
                                    <div class="card-body">
                                        <h5 class="card-title">@produto.NomeDoProduto</h5>
                                        <p class="card-text">Código do alimento: @produto.CodigoAlimento</p>
                                        <p class="card-text">Descrição: @produto.Descricao</p>
                                        <p class="card-text">Preço: R$@produto.Preco</p>
                                        <p class="card-text">Peso: @produto.Peso</p>
                                        <a class="btn btn-success d-block mb-2" asp-action="AdicionarProduto" asp-route-codigo="@produto.CodigoAlimento">Adicionar ao carrinho</a>
                                        <a class="btn btn-success d-block" asp-controller="Checkout" asp-action="Pagamento">Comprar produto</a>
                                    </div>
                                </div>
                            </div>
                        }
                        else
                        {
                            <div class="col">
                                <div class="card card-menu h-100">
                                    <img src="~/images/alimentos.jpg" class="card-img-top" alt="...">
                                    <div class="card-body">
                                        <h5 class="card-title">@produto.NomeDoProduto</h5>
                                        <p class="card-text">Código do alimento: @produto.CodigoAlimento</p>
                                        <p class="card-text">Descrição: @produto.Descricao</p>
                                        <p class="card-text">Preço: R$@produto.Preco</p>
                                        <p class="card-text">Peso: @produto.Peso</p>
                                        <a class="btn btn-success d-block mb-2" asp-action="AdicionarProduto" asp-route-codigo="@produto.CodigoAlimento">Adicionar ao carrinho</a>
                                        <a class="btn btn-success d-block" asp-controller="Checkout" asp-action="Pagamento">Comprar produto</a>
                                    </div>
                                </div>
                            </div>
                        }
                    }
                }
            </div>
        </div>
        <div class="tab-pane fade" id="verduras-tab-pane" role="tabpanel" aria-labelledby="verduras-tab" tabindex="0">
            <div class="row row-cols-1 row-cols-md-3 g-4">
                @foreach (var produto in Model)
                {
                    if (produto.Categoria.ToLower().Equals("verdura"))
                    {
                        if (produto.Imagem != null)
                        {
                            var base64 = Convert.ToBase64String(produto.Imagem);
                            var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                            <div class="col">
                                <div class="card card-menu h-100">
                                    <img src="@imgsrc" class="card-img-top" alt="...">
                                    <div class="card-body">
                                        <h5 class="card-title">@produto.NomeDoProduto</h5>
                                        <p class="card-text">Código do alimento: @produto.CodigoAlimento</p>
                                        <p class="card-text">Descrição: @produto.Descricao</p>
                                        <p class="card-text">Preço: R$@produto.Preco</p>
                                        <p class="card-text">Peso: @produto.Peso</p>
                                        <a class="btn btn-success d-block mb-2" asp-action="AdicionarProduto" asp-route-codigo="@produto.CodigoAlimento">Adicionar ao carrinho</a>
                                        <a class="btn btn-success d-block" asp-controller="Checkout" asp-action="Pagamento">Comprar produto</a>
                                    </div>
                                </div>
                            </div>
                        }
                        else
                        {
                            <div class="col">
                                <div class="card card-menu h-100">
                                    <img src="~/images/alimentos.jpg" class="card-img-top" alt="...">
                                    <div class="card-body">
                                        <h5 class="card-title">@produto.NomeDoProduto</h5>
                                        <p class="card-text">Código do alimento: @produto.CodigoAlimento</p>
                                        <p class="card-text">Descrição: @produto.Descricao</p>
                                        <p class="card-text">Preço: R$@produto.Preco</p>
                                        <p class="card-text">Peso: @produto.Peso</p>
                                        <a class="btn btn-success d-block mb-2" asp-action="AdicionarProduto" asp-route-codigo="@produto.CodigoAlimento">Adicionar ao carrinho</a>
                                        <a class="btn btn-success d-block" asp-controller="Checkout" asp-action="Pagamento">Comprar produto</a>
                                    </div>
                                </div>
                            </div>
                        }
                    }
                }
            </div>
        </div>
        <div class="tab-pane fade" id="raizes-tab-pane" role="tabpanel" aria-labelledby="raizes-tab" tabindex="0">
            <div class="row row-cols-1 row-cols-md-3 g-4">
                @foreach (var produto in Model)
                {
                    if (produto.Categoria.ToLower().Equals("raiz"))
                    {
                        if (produto.Imagem != null)
                        {
                            var base64 = Convert.ToBase64String(produto.Imagem);
                            var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                            <div class="col">
                                <div class="card card-menu h-100">
                                    <img src="@imgsrc" class="card-img-top" alt="...">
                                    <div class="card-body">
                                        <h5 class="card-title">@produto.NomeDoProduto</h5>
                                        <p class="card-text">Código do alimento: @produto.CodigoAlimento</p>
                                        <p class="card-text">Descrição: @produto.Descricao</p>
                                        <p class="card-text">Preço: R$@produto.Preco</p>
                                        <p class="card-text">Peso: @produto.Peso</p>
                                        <a class="btn btn-success d-block mb-2" asp-action="AdicionarProduto" asp-route-codigo="@produto.CodigoAlimento">Adicionar ao carrinho</a>
                                        <a class="btn btn-success d-block" asp-controller="Checkout" asp-action="Pagamento">Comprar produto</a>
                                    </div>
                                </div>
                            </div>
                        }
                        else
                        {
                            <div class="col">
                                <div class="card card-menu h-100">
                                    <img src="~/images/alimentos.jpg" class="card-img-top" alt="...">
                                    <div class="card-body">
                                        <h5 class="card-title">@produto.NomeDoProduto</h5>
                                        <p class="card-text">Código do alimento: @produto.CodigoAlimento</p>
                                        <p class="card-text">Descrição: @produto.Descricao</p>
                                        <p class="card-text">Preço: R$@produto.Preco</p>
                                        <p class="card-text">Peso: @produto.Peso</p>
                                        <a class="btn btn-success d-block mb-2" asp-action="AdicionarProduto" asp-route-codigo="@produto.CodigoAlimento">Adicionar ao carrinho</a>
                                        <a class="btn btn-success d-block" asp-controller="Checkout" asp-action="Pagamento">Comprar produto</a>
                                    </div>
                                </div>
                            </div>
                        }
                    }
                }
            </div>
        </div>
    </div>
</section>